version: "3"

services:
  graphql-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: zelda-item-tracker/server
    ports:
      - "4000:4000"
    env_file: "./server/.env"
    networks:
      - zelda-item-tracker

  react-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: zelda-item-tracker/app
    restart: always
    ports:
      - "5173:5173"
    env_file: "./client/.env"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - graphql-server
    networks:
      - zelda-item-tracker

networks:
  zelda-item-tracker:
    driver: bridge
